title = "Pieter Verweij"
base_url = "https://pieterverweij.nl/"
description = "Mijn eigen online plaatsje."

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
build_search_index = false
author = "Pieter Verweij"

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
# Sets theme and browser theme color,
# see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#00a2ff"
# Same as primary_color, but with 20% opacity
primary_color_alpha = "rgba(0, 160, 255, 0.2)"
# Emoji favicon; can be set per-page or even section.
emoji_favicon = false
# If the favicon is GIF or not
animated_favicon = false
# Tera date format (not used in comments!),
# see https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
# for all available variables.
date_format = "%d %B %Y"
# URL to issue tracker
issues_url = "mailto:website+issue@pieterverweij.nl"
# URL to website's source code
source_url = "https://codeberg.org/daudix/duckquill"
# Additional stylesheets; expects it to be in the ./static/ directory.
# If you are using Sass it will be compiled there anyway.
# stylesheets = [
#   "YOUR_STYLE.css",
#   "ALSO_YOUR_STYLE.css"
# ]

[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = false
# Links used in the nav
links = [
  {url = "$BASE_URL/contact", name = "Contact"},
]

[extra.footer]
# URL to the website without the https:// part, used for Johnvertisement leaderboard
johnvert_ref = "pieterverweij.nl"
# "© Title, YEAR" in the footer
show_copyright = true
# "Marketing" via "john" in the footer
show_johnvert = false
# "Powered by Zola and Duckquill" in footer
show_powered_by = true
# Link to website source
show_source = false
